pipeline:
   name: drone-testing
   identifier: drone_testing
   projectIdentifier: drone_testing
   orgIdentifier: jimexample
   properties:
      ci:
        codebase:
          build: <+input>
          connectorRef: account.Jim_Sheldon_GitHub
          repoName: drone-testing
    
   stages:
      - stage:
          variables:
            - name: CI
              type: String
              description: ""
              required: false
              value: "true"
            - name: CI_COMMIT_BRANCH
              type: String
              description: ""
              required: false
              value: <+codebase.branch>
            - name: DRONE
              type: String
              description: ""
              required: false
              value: "true"
            - name: DRONE_REPO_NAME
              type: String
              description: ""
              required: false
              value: <+codebase.repoUrl.split('/')[4]>
          identifier: default
          name: default
          spec:
            cloneCodebase: true
            sharedPaths:
              - /var/run
              - /var/lib/docker
            execution:
              steps:
              - step:
                  type: Background
                  name: dind
                  identifier: dind
                  spec:
                    connectorRef: account.YourConnector
                    image: docker:dind
                    shell: Sh
                    privileged: true
              - step:
                  type: Run
                  name: docker health
                  identifier: docker_health
                  spec:
                    connectorRef: account.Jim_Sheldon
                    image: plugins/docker
                    shell: Sh
                    command: |-
                      while ! docker ps ;do   
                        echo "Docker not available yet"
                        sleep 1 
                      done  
                      echo "Docker Service Ready"
              - step:
                  identifier: slack
                  name: slack
                  spec:
                    connectorRef: account.Jim_Sheldon
                    image: plugins/slack
                    settings:
                      webhook: <+secrets.getValue("MY_SLACK_WEBHOOK")>
                  timeout: ""
                  type: Plugin
              - step:
                  identifier: testslack
                  name: test slack
                  spec:
                    connectorRef: account.Jim_Sheldon
                    image: plugins/slack
                    settings:
                      channel: C05C45H2ATS
                      template: basic_success_1
                  timeout: ""
                  type: Plugin
              - step:
                  identifier: hello
                  name: hello
                  spec:
                    command: echo hello world
                    connectorRef: account.Jim_Sheldon
                    image: busybox
                  timeout: ""
                  type: Run
            platform:
              arch: Arm64
              os: Linux
            runtime:
              spec: {}
              type: Cloud
          type: CI
          when:
            condition: <+trigger.branch> == "main"
            pipelineStatus: Success
    
