---
pipeline:
    name: drone-testing
    identifier: drone_testing
    projectIdentifier: drone_testing
    orgIdentifier: jimexample
    description: Harness Pipeline created via Terraform
    "properties":
      "ci":
        "codebase":
          "build": "<+input>"
          "connectorRef": "account.Jim_Sheldon_GitHub"
          "repoName": "drone-testing"
    "stages":
    - "stage":
        "identifier": "default"
        "name": "default"
        "spec":
          "cloneCodebase": true
          "execution":
            "steps":
            - "step":
                "identifier": "hello"
                "name": "hello"
                "spec":
                  "command": "echo hello world"
                  "connectorRef": "account.Jim_Sheldon"
                  "image": "busybox"
                "timeout": ""
                "type": "Run"
          "infrastructure":
            "spec":
              "connectorRef": "account.macbook91"
              "namespace": "harness-delegate-ng"
            "type": "KubernetesDirect"
          "platform":
            "arch": "Amd64"
            "os": "Linux"
        "type": "CI"
        "when":
          "condition": "<+trigger.branch> == \"main\""
          "pipelineStatus": "Success"
    
