kind: pipeline
type: docker
name: default

platform:
  os: linux
  arch: arm64

steps:

- name: slack
  image: plugins/slack
  settings:
    webhook:
      from_secret: MY_SLACK_WEBHOOK

- name: eoin slack
  image: plugins/slack
  environment:
    SLACK_ACCESS_TOKEN:
      from_secret: EOIN_SLACK_TOKEN
  settings:
    channel: C05C45H2ATS

- name: hello
  image: busybox
  commands:
  - echo hello world
 
trigger:
  branch:
  - main
  
