kind: pipeline
type: docker
name: default

platform:
  os: linux
  arch: arm64

steps:
- name: hello
  image: busybox
  commands:
  - echo hello world

- name: tag
  image: busybox
  commands:
  - echo this is a tag
  when:
    event:
    - tag

trigger:
  branch:
  - main
  - refs/tags/v*
  
