kind: pipeline
type: kubernetes
name: default

steps:

- name: docker
  image: plugins/kaniko
  settings:
    repo: jimsheldon/drone-testing
    username: jimsheldon
    password:
      from_secret: docker_password

trigger:
  branch:
  - main
