kind: pipeline
type: kubernetes
name: default

steps:

- name: env
  image: busybox
  environment:
    MY_VAR: ${DRONE_BUILD_NUMBER}-${DRONE_COMMIT_SHA}
  commands:
  - env
 
trigger:
  branch:
  - main
