kind: pipeline
type: kubernetes
name: default

steps:
- name: hello
  image: busybox
  commands:
  - echo hello world
  when:
    event:
    - push
    - pull_request

- name: tag
  image: busybox
  commands:
  - echo this is a tag
  when:
    event:
    - tag

trigger:
  branch:
  - main
  event:
  - pull_request
  
