kind: pipeline
type: docker
name: default

platform:
  os: linux
  arch: arm64

steps:

- name: hello
  image: busybox
  environment:
    MY_VAR: $DRONE_BUILD_NUMBER-$DRONE_COMMIT_SHA
  commands:
  - env
 
trigger:
  branch:
  - main
  
